### ISSUE TITLE
About PQ in baseline

### ISSUE THREAD

**Issue by JasonRichard** [TissueImageAnalytics/CoNIC#4]
Could you please explain how _PQ_ is calculate in baseline？
Given _semantic_predictions_ and _semantic_true_ in baseline
I can get _mPQ+_ = 0.49975367875956067 ≈ 0.4998 as given.
However, I cannot get PQ right (0.6149) as shown in the table.
Does is mean _Binary PQ_ described in [Lizard](https://arxiv.org/abs/2108.11195)？

Given _semantic_predictions_ and _semantic_true_ in baseline, when calculating pq by pitcture
1018 samples decrease to 982, meaning there are 36 patches get iou_sum/(tp+0.5*fp+0.5*fn) as infinate.
there is nothing to predict (cropped blank from origin picture or no nuclei in it)
eg. patches from dataset pannuke images No. 1,4,6,11 etc.

Or is there something I mistake. Plz point out.

Best regards!

**Comment by vqdang** [comment]
Which function did you use to calculate?

The values in the notebook were measured using this
> https://github.com/TissueImageAnalytics/CoNIC/blob/main/compute_stats.py

Also,
```
Given semantic_predictions and semantic_true in baseline, when calculating pq by pitcture
1018 samples decrease to 982, meaning there are 36 patches get iou_sum/(tp+0.5fp+0.5fn) as infinate.
there is nothing to predict (cropped blank from origin picture or no nuclei in it)
eg. patches from dataset pannuke images No. 1,4,6,11 etc.
```
because we inevitably have pictures that do not contain some types. For CoNIC, we combine the FP TP FN etc. across all images first before using it to get the mPQ, you can refer to https://arxiv.org/abs/2111.14485 for the formulation here.

About the PQ only [here](https://github.com/TissueImageAnalytics/CoNIC/blob/2e153be18e152e2a215dfd638b70395bf1fbca00/metrics/stats_utils.py#L61), we add epsilon into the formulas 

https://github.com/TissueImageAnalytics/CoNIC/blob/2e153be18e152e2a215dfd638b70395bf1fbca00/metrics/stats_utils.py#L168-L170

so I do not think there should be anything exploding to NaN or infinity (`paired_iou` should not be that much smaller than 1.0e-6).

Can you provide more details on your setup?

**Comment by JasonRichard** [comment]
Much appreciated！Now I understand how they work.

I might have made it wrong by mixing `get_multi_pq_info` and `get_pq` (in `matrix/stats_utils.py`) together. 

> because we inevitably have pictures that do not contain some types.

Not just some types, there are **patches that are no nuclei at all**. I simply **skipped** them without calculation.
Because all of `tp, fp, fn` and `paired_iou` are treated 0 in those patches(from method `get_pq`), as background label 0 are excluded in `pairwise_iou`. However, SQ, DQ and PQ should not be treated such, meaning the model prediction is bad. And it's not model's fault but 'badly cropped' patches from original picture.

Neither they treated as 1 or the patch skipped is more convincing for me, and more consistent with SQ, DQ and PQ's defined meaning. 

Issue will be closed for its rare occurrence and `mPQ+` metric avoids this strange circumstance.
